name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install libsdl2-dev
    - name: make
      run: make
    - name: upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          playmidi
          playmidi.1*
