name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu', 'macos']
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install libsdl2-dev
    - name: install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install sdl2
    - name: make
      run: make
